### ISSUE TITLE
Misleading verbose output

### ISSUE THREAD

**Issue by thowell332** [almost-matching-exactly/DAME-FLAME-Python-Package#10]
For `verbose = 3`, the output starts with iteration 2 (skipping over the first iteration which checks for exact matches) which could be misleading for some users.

**Comment by nehargupta** [comment]
Assigned to Angikar. Can't tag him because he isn't a "contributor" yet

**Comment by AngikarGhosal** [comment]
This has been completed.

**Comment by nehargupta** [comment]
done
