### ISSUE TITLE
Valid input checking on non-integer

### ISSUE THREAD

**Issue by nehargupta** [almost-matching-exactly/DAME-FLAME-Python-Package#13]
Make sure that if a user inputs any non-integer values (including floats!!), that its not allowed.

**Comment by neil007m** [comment]
Happy to contribute if needed.

**Comment by nehargupta** [comment]
> Happy to contribute if needed.

Hi @neil007m, Thanks for reaching out. I think our team has most of our development needs figured out so this specific bug isn't something we're looking for a contributor for. But, we're definitely trying to get the package more widely used and looking for users, or feedback on the usability. If you fork the repo and play around with it, feel free to file a new bug if you notice an issue, have questions, want an enhancement, or find documentation unclear in any way. Thanks!

**Comment by neil007m** [comment]
@nehargupta Sounds good!

**Comment by nehargupta** [comment]
Assigned to Angikar. Can't tag him because he isn't a "contributor" yet

**Comment by AngikarGhosal** [comment]
Resolved

**Comment by nehargupta** [comment]
Actually, I'm now realizing that categorical data (ie 'a') is alright in the case of adaptive_weights='decision-tree' so need to keep that in mind in this improvement!

**Comment by nehargupta** [comment]
Hi @neil007m, thanks for reaching out a few weeks ago. We finally have a contributing guide up on our docs [here](https://almost-matching-exactly.github.io/DAME-FLAME-Python-Package/getting-started/contributing_guide/)! If you see anything that you want to work on, please follow that guide, and let our team know if you have questions or want help. We really want this to be easy for new contributors to participate/contribute and your work is welcome and appreciated.

**Comment by nehargupta** [comment]
Should be fixed with the push I'm making in a couple minutes.
