### ISSUE TITLE
'total_treated' used in verbose statements is misleading as df_all gets changed at line 143 for repeats==False. 

### ISSUE THREAD

**Issue by VaishaliJain** [almost-matching-exactly/DAME-FLAME-Python-Package#3]
https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/b0124da9166e2632c7ca104da40eddf5055f5262/dame_flame/dame_algorithm.py#L293

**Comment by nehargupta** [comment]
changed locally

**Comment by nehargupta** [comment]
pushed fix. need to check for similar issue in flame_algorithm.py

**Comment by nehargupta** [comment]
Fixed!
