### ISSUE TITLE
early_stops.un_t_frac and early_stops.un_c_frac is a fraction. Do we ever set it to a boolean?

### ISSUE THREAD

**Issue by VaishaliJain** [almost-matching-exactly/DAME-FLAME-Python-Package#4]
https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/b0124da9166e2632c7ca104da40eddf5055f5262/dame_flame/dame_algorithm.py#L194

**Comment by vittorioorlandi** [comment]
The default is `False`. It should be changed to 0.0 (@nehargupta).
