### ISSUE TITLE
ENH: Move to 0-indexing?

### ISSUE THREAD

**Issue by nickeubank** [almost-matching-exactly/DAME-FLAME-Python-Package#48]
Don't get me wrong, I'm a social scientist and prefer 1-indexing (e.g. love me some Julia!). But Python *is* a zero-indexed language, so maybe move everything to zero indexing to address #32 and #47 ? Note will require change in output message header, rollback of #33, and changing `early_stop_iterations` keyword.

**Comment by nehargupta** [comment]
@haoningjiang If you could look into this, would be a huge help! Please do ask questions here or on slack.

**Comment by nehargupta** [comment]
@haoningjiang Thanks for looking into this! The "iteration counter" is named h in the dame_algorithm.py and flame_algorithm.py files (feel free to rename this variable if you want). Having it start at 0 should be good -- but definitely do some testing to make sure changes have been made at all necessary places

https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/master/dame_flame/dame_algorithm.py#L289
https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/master/dame_flame/dame_algorithm.py#L300
https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/master/dame_flame/flame_algorithm.py#L260
https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/master/dame_flame/flame_algorithm.py#L181
