### ISSUE TITLE
Misleading as 'df_all' is getting changed for repeats==False at line 143

### ISSUE THREAD

**Issue by VaishaliJain** [almost-matching-exactly/DAME-FLAME-Python-Package#5]
https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/b0124da9166e2632c7ca104da40eddf5055f5262/dame_flame/dame_algorithm.py#L223

**Comment by nehargupta** [comment]
changed locally

**Comment by nehargupta** [comment]
pushed fix. need to check for similar issue in flame_algorithm.py

**Comment by nehargupta** [comment]
This is fixed!
