### ISSUE TITLE
Unable to install on windows 

### ISSUE THREAD

**Issue by custos-notitia** [almost-matching-exactly/DAME-FLAME-Python-Package#54]
I could not install on windows (10) with pip or conda. The only way I could get it to load was by downloading the .whl and installing from local (using pip). This might explain why pypistats shows all Linux. https://pypistats.org/packages/dame-flame

**Comment by nehargupta** [comment]
Hi @datagub, 
Sorry to hear you encountered issues in downloading and glad you got it figured out. 

I have always been able to install on windows 10 with standard pip commands, when running a terminal through Anaconda. So, if you have any further details to replicate or recommendations on how to solve this issue, please let me know. 

Thanks, and if you have any questions or issues as you use the package, also happy to help with that.

**Comment by nehargupta** [comment]
Hi @custos-notitia I'm closing this issue...Like I said, I've never had issues installing on windows10 with pip so I would maybe need more detail to be able to replicate this issue, but please let me know if you continue to have installation problems or discover any issues, happy to help. Thanks!
