### ISSUE TITLE
It is being changed at line 143 and creates a lot of confusion in log/print statements.

### ISSUE THREAD

**Issue by VaishaliJain** [almost-matching-exactly/DAME-FLAME-Python-Package#6]
https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/b0124da9166e2632c7ca104da40eddf5055f5262/dame_flame/dame_algorithm.py#L86

**Comment by nehargupta** [comment]
Fixed locally

**Comment by nehargupta** [comment]
pushed fix. need to check for similar issue in flame_algorithm.py

**Comment by nehargupta** [comment]
Fixed!
