### ISSUE TITLE
We need weights array only if adaptive_weights = False

### ISSUE THREAD

**Issue by VaishaliJain** [almost-matching-exactly/DAME-FLAME-Python-Package#7]
https://github.com/almost-matching-exactly/DAME-FLAME-Python-Package/blob/b0124da9166e2632c7ca104da40eddf5055f5262/dame_flame/DAME_FLAME.py#L57

**Comment by guptane6** [comment]
Thanks! Changed locally.

**Comment by nehargupta** [comment]
Issue fixed
