### ISSUE TITLE
Error? "Matching stopped while attempting iteration 1 due to the PE fraction early stopping criterion."

### ISSUE THREAD

**Issue by cignals24** [almost-matching-exactly/DAME-FLAME-Python-Package#74]
Hi.  I am excited to use this package but having spent a few hours with it today and I am having trouble recreating the examples in the documentation. For instance, from here:
https://almost-matching-exactly.github.io/DAME-FLAME-Python-Package/examples/interpretability/

I am only getting not even one iteration? and the example has 5? 

**Using this code:** 

import dame_flame
import numpy as np
import matplotlib.pyplot as plt
df,_ = dame_flame.utils.data.generate_binomial_decay_importance(50,50)
model = dame_flame.matching.FLAME(verbose=3, repeats=False)
model.fit(holdout_data=df)
result_flame = model.predict(df)

**OUTPUT looks wrong**

Completed iteration 0 of matching
	Number of matched groups formed in total:  26
	Unmatched treated units:  4 out of a total of  50 treated units
	Unmatched control units:  2 out of a total of  50 control units
	Number of matches made this iteration:  94
	Number of matches made so far:  94
	Covariates dropped so far:  set()
	Predictive error of covariate set used to match:  0.010168386437667723
Matching stopped while attempting iteration 1 due to the PE fraction early stopping criterion.
	Predictive error of covariate set would have been 0.3628045613492125

**Setup**
using DBX
%pip install dame-flame==0.71
sys version 3.10.12

**Comment by nehargupta** [comment]
Hi @cignals24 
Thanks so much for your excitement and interest in using the package! I apologize for the delay in getting back to you.
 
Our documentation webpage is out of date unfortunately  -- there has been an update to the default functionality of the early_stop_pe parameter, which now stops after a big jump in PE (predictive error) to prevent matches that are low-quality. This parameter can be changed if you want it to match to completion. 

That example you're seeing was posted prior to the default functionality update. So it should be working but please let me know if you find any other errors! The most up to date parameters are here: https://arxiv.org/pdf/2101.01867
